# Generated by Django 4.0.1 on 2022-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid1', models.CharField(max_length=10000)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
