# Generated by Django 4.0.1 on 2022-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uuid_', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuid',
            old_name='uuid1',
            new_name='uuid_str',
        ),
        migrations.AlterField(
            model_name='uuid',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
